
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace lampbae_final_project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Friend
{

    public int ConnectionID { get; set; }

    public string UserID1 { get; set; }

    public string UserID2 { get; set; }

}

}
