//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lampbae_final_project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LampBaeEntities1 : DbContext
    {
        public LampBaeEntities1()
            : base("name=LampBaeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Listing> Listings { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<ViewCount> ViewCounts { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
