
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace lampbae_final_project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Listing
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Listing()
    {

        this.Favorites = new HashSet<Favorite>();

        this.Ratings = new HashSet<Rating>();

        this.Reports = new HashSet<Report>();

    }


    public int ID { get; set; }

    public string EbayItemNumber { get; set; }

    public string Title { get; set; }

    public string PostalCode { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<decimal> Price { get; set; }

    public string Email { get; set; }

    public string Image { get; set; }

    public Nullable<int> Rating { get; set; }

    public Nullable<int> ReportCount { get; set; }

    public string ItemSearchURL { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Favorite> Favorites { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rating> Ratings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Report> Reports { get; set; }

}

}
