
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace lampbae_final_project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Rating
{

    public string UserID { get; set; }

    public Nullable<int> ItemID { get; set; }

    public Nullable<int> Rating1 { get; set; }

    public int RatingID { get; set; }



    public virtual Listing Listing { get; set; }

}

}
